version: "3"

services:
  mongodb:
    container_name: mongodb
    build: .\mongodb\.
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
      MONGO_INITDB_DATABASE: countdown
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"

  next-app:
    container_name: countdown-webapp
    build: .
    environment:
      DATABASE_URL: mongodb://user:user@localhost:27017/mongo?authSource=admin
      NEXTAUTH_SECRET: "generate sercet for nextauth "
      NEXTAUTH_UR: "localhost:3000"
      TMDB_API_KEY: "themoviedb.org api key"
    ports:
      - 3000:3000
    volumes:
      - .:/app
    restart: always
