version: "3"

services:
  next-app:
    container_name: next-app
    image: docker.io/library/nextjs_countdown_app:latest

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
networks:
  my_network:
    external: true
