name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: cancel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get -yqq install docker-compose
          docker-compose version

      # - name: Build and push Docker image
      #   run: |
      #     echo "${{ secrets.DOCKERPW }}" | docker login -u "mahdiidrissidev" --password-stdin
      #     docker image build -t mahdiidrissidev/nextjs_countdown_app_dev:latest .
      #     docker push mahdiidrissidev/nextjs_countdown_app_dev:latest

      - name: Run Docker Compose
        run: |
          docker-compose up -d
          docker-compose ps

      - name: Install jq (if not installed)
        run: sudo apt-get -yqq install jq

      - uses: luisboto/ngrok-tunnel-action@<VERSION>
        with:
          timeout: 1h
          port: 8080
          ngrok_authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
          tunnel_type: http
          save_url_to_filename: tunnelURL.md
