name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      ngrok:
        image: wernight/ngrok
        ports:
          - "4040:4040"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get -yqq install docker-compose
          docker-compose version

      # - name: Build and push Docker image
      #   run: |
      #     echo "${{ secrets.DOCKERPW }}" | docker login -u "mahdiidrissidev" --password-stdin
      #     docker image build -t mahdiidrissidev/nextjs_countdown_app_dev:latest .
      #     docker push mahdiidrissidev/nextjs_countdown_app_dev:latest

      - name: Run Docker Compose
        run: |
          docker-compose up -d
          docker-compose ps

      - name: Install jq (if not installed)
        run: sudo apt-get -yqq install jq

      - name: Expose ngrok tunnel
        run: |
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
          echo "Ngrok URL: $NGROK_URL"
