name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    env:
      MY_ENV_VAR: "${{ secrets.DOCKERPW }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
