name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    env:
      DATABASE_URL: "${{ secrets.DATABASE_URL }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass the project ID from the secrets through environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
